/**
 * Urban Noise Telemetry Dataset - Top 10 Major Indian Metropolises
 * Supports Chennai, Coimbatore, Bangalore, Mumbai, Pune, Delhi NCR, Hyderabad, Kolkata, Ahmedabad, Jaipur.
 */

export const SLUG_TO_CITY_ID = {
  chn: "chennai",
  chennai: "chennai",
  cbe: "coimbatore",
  coimbatore: "coimbatore",
  blr: "bangalore",
  bangalore: "bangalore",
  mum: "mumbai",
  mumbai: "mumbai",
  pun: "pune",
  pune: "pune",
  del: "delhi",
  delhi: "delhi",
  hyd: "hyderabad",
  hyderabad: "hyderabad",
  kol: "kolkata",
  kolkata: "kolkata",
  ahm: "ahmedabad",
  ahmedabad: "ahmedabad",
  jai: "jaipur",
  jaipur: "jaipur"
};

export const CITY_ID_TO_SLUG = {
  chennai: "chn",
  coimbatore: "cbe",
  bangalore: "blr",
  mumbai: "mum",
  pune: "pun",
  delhi: "del",
  hyderabad: "hyd",
  kolkata: "kol",
  ahmedabad: "ahm",
  jaipur: "jai"
};

export const INDIAN_CITIES = [
  {
    id: "chennai",
    slug: "chn",
    name: "Chennai",
    state: "Tamil Nadu",
    landmark: "Marina Beach",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80",
    gradient: "from-blue-600 to-teal-500",
    center: [13.0499, 80.2824],
    accentColor: "#3B82F6",
    avgDb: 64.8,
    maxDb: 78.4,
    activeSensors: 14,
    violationsCount: 6
  },
  {
    id: "coimbatore",
    slug: "cbe",
    name: "Coimbatore",
    state: "Tamil Nadu",
    landmark: "Gandhipuram Clock Tower",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80",
    gradient: "from-emerald-600 to-teal-600",
    center: [11.0183, 76.9644],
    accentColor: "#10B981",
    avgDb: 58.4,
    maxDb: 69.2,
    activeSensors: 10,
    violationsCount: 2
  },
  {
    id: "bangalore",
    slug: "blr",
    name: "Bangalore",
    state: "Karnataka",
    landmark: "Vidhana Soudha",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=600&q=80",
    gradient: "from-purple-600 to-indigo-600",
    center: [12.9796, 77.5906],
    accentColor: "#8B5CF6",
    avgDb: 68.2,
    maxDb: 84.6,
    activeSensors: 18,
    violationsCount: 9
  },
  {
    id: "mumbai",
    slug: "mum",
    name: "Mumbai",
    state: "Maharashtra",
    landmark: "Gateway of India",
    image: "https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=600&q=80",
    gradient: "from-amber-600 to-orange-600",
    center: [18.9220, 72.8347],
    accentColor: "#F59E0B",
    avgDb: 73.5,
    maxDb: 91.2,
    activeSensors: 22,
    violationsCount: 14
  },
  {
    id: "pune",
    slug: "pun",
    name: "Pune",
    state: "Maharashtra",
    landmark: "Shaniwar Wada",
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?auto=format&fit=crop&w=600&q=80",
    gradient: "from-rose-600 to-pink-600",
    center: [18.5196, 73.8553],
    accentColor: "#F43F5E",
    avgDb: 61.9,
    maxDb: 74.8,
    activeSensors: 12,
    violationsCount: 4
  },
  {
    id: "delhi",
    slug: "del",
    name: "Delhi NCR",
    state: "National Capital Region",
    landmark: "India Gate",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80",
    gradient: "from-cyan-600 to-blue-700",
    center: [28.6129, 77.2295],
    accentColor: "#06B6D4",
    avgDb: 71.4,
    maxDb: 88.9,
    activeSensors: 20,
    violationsCount: 11
  },
  {
    id: "hyderabad",
    slug: "hyd",
    name: "Hyderabad",
    state: "Telangana",
    landmark: "Charminar",
    image: "https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=600&q=80",
    gradient: "from-indigo-600 to-cyan-600",
    center: [17.3616, 78.4747],
    accentColor: "#6366F1",
    avgDb: 65.1,
    maxDb: 79.5,
    activeSensors: 15,
    violationsCount: 7
  },
  {
    id: "kolkata",
    slug: "kol",
    name: "Kolkata",
    state: "West Bengal",
    landmark: "Howrah Bridge",
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=600&q=80",
    gradient: "from-orange-600 to-yellow-600",
    center: [22.5851, 88.3468],
    accentColor: "#EA580C",
    avgDb: 67.8,
    maxDb: 83.1,
    activeSensors: 14,
    violationsCount: 8
  },
  {
    id: "ahmedabad",
    slug: "ahm",
    name: "Ahmedabad",
    state: "Gujarat",
    landmark: "Sabarmati Riverfront",
    image: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=600&q=80",
    gradient: "from-red-600 to-amber-600",
    center: [23.0300, 72.5800],
    accentColor: "#EF4444",
    avgDb: 62.7,
    maxDb: 76.0,
    activeSensors: 11,
    violationsCount: 5
  },
  {
    id: "jaipur",
    slug: "jai",
    name: "Jaipur",
    state: "Rajasthan",
    landmark: "Hawa Mahal",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80",
    gradient: "from-pink-600 to-rose-500",
    center: [26.9239, 75.8267],
    accentColor: "#EC4899",
    avgDb: 59.8,
    maxDb: 72.3,
    activeSensors: 9,
    violationsCount: 3
  }
];

export const INITIAL_MOCK_READINGS = [
  // --- CHENNAI ---
  {
    id: "che-101",
    city: "chennai",
    latitude: 13.0405,
    longitude: 80.2337,
    decibel_level: 78.4,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "T. Nagar Ranganathan St Corner (IoT #1)",
    notes: "Dense pedestrian surge & heavy bus accelerating at junction",
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "che-102",
    city: "chennai",
    latitude: 13.0878,
    longitude: 80.2170,
    decibel_level: 82.6,
    source_type: "iot_sensor",
    category: "construction",
    location_name: "Anna Nagar Roundtana Metro Work (IoT #2)",
    notes: "Heavy piling rig & concrete breaker active on main road",
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "che-103",
    city: "chennai",
    latitude: 12.9780,
    longitude: 80.2412,
    decibel_level: 74.2,
    source_type: "crowdsourced",
    category: "traffic",
    location_name: "Velachery Bypass Flyover Junction",
    notes: "Peak hour two-wheeler traffic honking & bus congestion",
    timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "che-104",
    city: "chennai",
    latitude: 13.0102,
    longitude: 80.2156,
    decibel_level: 86.8,
    source_type: "iot_sensor",
    category: "industrial",
    location_name: "Guindy Industrial Estate Phase 1",
    notes: "Heavy metal fabrication press & generator exhaust",
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "che-105",
    city: "chennai",
    latitude: 13.0489,
    longitude: 80.2825,
    decibel_level: 44.5,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Marina Beach Service Road Acoustic Station",
    notes: "Ocean breeze baseline acoustic reserve sensor",
    timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
    severity: "safe"
  },
  {
    id: "che-106",
    city: "chennai",
    latitude: 12.9890,
    longitude: 80.2490,
    decibel_level: 47.8,
    source_type: "crowdsourced",
    category: "ambient",
    location_name: "Adyar Eco Park Reserve Boundary",
    notes: "Quiet bird sanctuary boundary sound monitor",
    timestamp: new Date(Date.now() - 50 * 60000).toISOString(),
    severity: "safe"
  },
  {
    id: "che-107",
    city: "chennai",
    latitude: 12.9692,
    longitude: 80.2458,
    decibel_level: 68.3,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "OMR IT Corridor Taramani Toll",
    notes: "Continuous IT shuttle bus & car stream",
    timestamp: new Date(Date.now() - 70 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "che-108",
    city: "chennai",
    latitude: 13.0901,
    longitude: 80.2882,
    decibel_level: 71.5,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Parry's Corner Commercial Plaza",
    notes: "Market public address speakers & auto horns",
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    severity: "violation"
  },

  // --- COIMBATORE ---
  {
    id: "cbe-201",
    city: "coimbatore",
    latitude: 11.0183,
    longitude: 76.9644,
    decibel_level: 76.5,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Gandhipuram Central Bus Stand Signal (IoT #1)",
    notes: "Intercity mofussil bus engine noise & peak horn pressure",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "cbe-202",
    city: "coimbatore",
    latitude: 11.0085,
    longitude: 76.9512,
    decibel_level: 62.4,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "RS Puram DB Road Shopping Strip",
    notes: "Moderate commercial car traffic & retail ambience",
    timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "cbe-203",
    city: "coimbatore",
    latitude: 11.0285,
    longitude: 77.0268,
    decibel_level: 66.8,
    source_type: "iot_sensor",
    category: "industrial",
    location_name: "TIDEL Park IT & Foundry Belt Peelamedu",
    notes: "Textile machinery transformer & tech park HVAC units",
    timestamp: new Date(Date.now() - 28 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "cbe-204",
    city: "coimbatore",
    latitude: 10.9954,
    longitude: 76.9602,
    decibel_level: 79.8,
    source_type: "crowdsourced",
    category: "construction",
    location_name: "Ukkadam Flyover Extension Site",
    notes: "Heavy excavator pile driver operations",
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "cbe-205",
    city: "coimbatore",
    latitude: 11.0020,
    longitude: 76.9740,
    decibel_level: 41.8,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Race Course Walkway Green Zone",
    notes: "Park promenade morning ambient quiet baseline",
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    severity: "safe"
  },
  {
    id: "cbe-206",
    city: "coimbatore",
    latitude: 11.0142,
    longitude: 76.9580,
    decibel_level: 64.1,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Town Hall Commercial Market",
    notes: "Textile shop sound promo announcements",
    timestamp: new Date(Date.now() - 80 * 60000).toISOString(),
    severity: "moderate"
  },

  // --- BANGALORE ---
  {
    id: "blr-301",
    city: "bangalore",
    latitude: 12.9172,
    longitude: 77.6228,
    decibel_level: 87.5,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Silk Board Flyover Junction (IoT #1)",
    notes: "Severe bottleneck traffic honking, diesel trucks & BMTC buses",
    timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "blr-302",
    city: "bangalore",
    latitude: 12.9756,
    longitude: 77.6066,
    decibel_level: 81.2,
    source_type: "iot_sensor",
    category: "construction",
    location_name: "MG Road Metro Interchange Station",
    notes: "Underground tunnel boring auxiliary generator",
    timestamp: new Date(Date.now() - 11 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "blr-303",
    city: "bangalore",
    latitude: 12.9784,
    longitude: 77.6408,
    decibel_level: 75.6,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Indiranagar 100ft Road Club District",
    notes: "Open rooftop bar live acoustics sound leak",
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "blr-304",
    city: "bangalore",
    latitude: 12.8452,
    longitude: 77.6602,
    decibel_level: 70.4,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Electronic City Expressway Toll",
    notes: "High speed cab corridor & tech park shuttles",
    timestamp: new Date(Date.now() - 38 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "blr-305",
    city: "bangalore",
    latitude: 12.9763,
    longitude: 77.5929,
    decibel_level: 42.0,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Cubbon Park Bamboo Grove Reserve",
    notes: "Protected eco quiet zone zero motor baseline",
    timestamp: new Date(Date.now() - 50 * 60000).toISOString(),
    severity: "safe"
  },
  {
    id: "blr-306",
    city: "bangalore",
    latitude: 12.9352,
    longitude: 77.6245,
    decibel_level: 69.8,
    source_type: "crowdsourced",
    category: "traffic",
    location_name: "Koramangala 80ft Road Junction",
    notes: "Food delivery two-wheeler swarm noise",
    timestamp: new Date(Date.now() - 75 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "blr-307",
    city: "bangalore",
    latitude: 12.9698,
    longitude: 77.7500,
    decibel_level: 83.1,
    source_type: "iot_sensor",
    category: "industrial",
    location_name: "Whitefield IT & Export Industrial Zone",
    notes: "Substation heavy transformer hum & chillers",
    timestamp: new Date(Date.now() - 95 * 60000).toISOString(),
    severity: "violation"
  },

  // --- MUMBAI ---
  {
    id: "mum-401",
    city: "mumbai",
    latitude: 19.0178,
    longitude: 72.8478,
    decibel_level: 89.4,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Dadar TT Circle Flyover (IoT #1)",
    notes: "Extreme high decibel horn pressure & BEST bus congestion",
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "mum-402",
    city: "mumbai",
    latitude: 19.0657,
    longitude: 72.8686,
    decibel_level: 77.8,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Bandra Kurla Complex (BKC) Connector",
    notes: "Corporate taxi rush & airport road vehicle stream",
    timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "mum-403",
    city: "mumbai",
    latitude: 19.1197,
    longitude: 72.8464,
    decibel_level: 84.5,
    source_type: "iot_sensor",
    category: "construction",
    location_name: "Andheri Western Express Highway Metro",
    notes: "Girders placement heavy crane hydraulics",
    timestamp: new Date(Date.now() - 24 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "mum-404",
    city: "mumbai",
    latitude: 18.9432,
    longitude: 72.8230,
    decibel_level: 56.2,
    source_type: "crowdsourced",
    category: "ambient",
    location_name: "Marine Drive Promenade",
    notes: "Sea breeze evening acoustic monitor",
    timestamp: new Date(Date.now() - 36 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "mum-405",
    city: "mumbai",
    latitude: 18.9950,
    longitude: 72.8300,
    decibel_level: 81.0,
    source_type: "iot_sensor",
    category: "industrial",
    location_name: "Lower Parel Commercial Mill Precinct",
    notes: "High capacity HVAC plant & ventilation shafts",
    timestamp: new Date(Date.now() - 55 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "mum-406",
    city: "mumbai",
    latitude: 19.0820,
    longitude: 72.8890,
    decibel_level: 86.2,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Kurla CST Road Festival Square",
    notes: "High wattage procession loudspeakers",
    timestamp: new Date(Date.now() - 70 * 60000).toISOString(),
    severity: "violation"
  },

  // --- PUNE ---
  {
    id: "pun-501",
    city: "pune",
    latitude: 18.5204,
    longitude: 73.8431,
    decibel_level: 74.8,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "FC Road Deccan Gymkhana (IoT #1)",
    notes: "Youth sports bike exhaust & student vehicle traffic",
    timestamp: new Date(Date.now() - 6 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "pun-502",
    city: "pune",
    latitude: 18.5912,
    longitude: 73.7389,
    decibel_level: 68.5,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Hinjewadi IT Park Phase 1 Circle",
    notes: "IT company bus fleets & cab dropoff zone",
    timestamp: new Date(Date.now() - 17 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "pun-503",
    city: "pune",
    latitude: 18.5018,
    longitude: 73.8636,
    decibel_level: 80.4,
    source_type: "iot_sensor",
    category: "construction",
    location_name: "Swargate Underground Metro Station",
    notes: "Sub-surface excavation drill & concrete mixer trucks",
    timestamp: new Date(Date.now() - 29 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "pun-504",
    city: "pune",
    latitude: 18.5520,
    longitude: 73.9120,
    decibel_level: 45.2,
    source_type: "crowdsourced",
    category: "ambient",
    location_name: "Viman Nagar Joggers Park Sanctuary",
    notes: "Residential park acoustic quiet sensor",
    timestamp: new Date(Date.now() - 48 * 60000).toISOString(),
    severity: "safe"
  },
  {
    id: "pun-505",
    city: "pune",
    latitude: 18.5080,
    longitude: 73.8050,
    decibel_level: 63.8,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Kothrud Karve Road Commercial Strip",
    notes: "Market audio ads & retail store speakers",
    timestamp: new Date(Date.now() - 65 * 60000).toISOString(),
    severity: "moderate"
  },

  // --- DELHI NCR ---
  {
    id: "del-601",
    city: "delhi",
    latitude: 28.6315,
    longitude: 77.2167,
    decibel_level: 83.4,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Connaught Place Inner Circle (IoT #1)",
    notes: "Continuous horn pressure & luxury car acceleration",
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "del-602",
    city: "delhi",
    latitude: 28.4950,
    longitude: 77.0890,
    decibel_level: 79.1,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Cyber City Rapid Metro Gurgaon",
    notes: "Rapid metro track squeal & corporate cabs",
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "del-603",
    city: "delhi",
    latitude: 28.5700,
    longitude: 77.3200,
    decibel_level: 81.6,
    source_type: "iot_sensor",
    category: "construction",
    location_name: "Noida Sector 18 Market Flyover Work",
    notes: "Pile driving & structural steel welding generators",
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "del-604",
    city: "delhi",
    latitude: 28.5933,
    longitude: 77.2197,
    decibel_level: 41.5,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Lodhi Gardens Acoustic Sanctuary",
    notes: "Heritage garden quiet sanctuary baseline",
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
    severity: "safe"
  },
  {
    id: "del-605",
    city: "delhi",
    latitude: 28.6562,
    longitude: 77.2301,
    decibel_level: 86.0,
    source_type: "crowdsourced",
    category: "traffic",
    location_name: "Chandni Chowk Wholesale Market",
    notes: "E-rickshaw horn clusters & cargo loader clamor",
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    severity: "violation"
  },

  // --- HYDERABAD ---
  {
    id: "hyd-701",
    city: "hyderabad",
    latitude: 17.4435,
    longitude: 78.3772,
    decibel_level: 77.2,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "HITEC City Cyber Towers Junction (IoT #1)",
    notes: "IT tech park bus queue & high density traffic",
    timestamp: new Date(Date.now() - 7 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "hyd-702",
    city: "hyderabad",
    latitude: 17.3616,
    longitude: 78.4747,
    decibel_level: 80.5,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Charminar Heritage Pedestrian Plaza",
    notes: "Bazaar sound amplifiers & tourist crowd noise",
    timestamp: new Date(Date.now() - 19 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "hyd-703",
    city: "hyderabad",
    latitude: 17.4400,
    longitude: 78.3480,
    decibel_level: 84.1,
    source_type: "iot_sensor",
    category: "construction",
    location_name: "Gachibowli Financial District Flyover",
    notes: "Flyover pre-cast segment hoist crane engines",
    timestamp: new Date(Date.now() - 32 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "hyd-704",
    city: "hyderabad",
    latitude: 17.4200,
    longitude: 78.4350,
    decibel_level: 43.8,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "KBR National Park Forest Perimeter",
    notes: "National park acoustic quiet zone baseline sensor",
    timestamp: new Date(Date.now() - 52 * 60000).toISOString(),
    severity: "safe"
  },

  // --- KOLKATA ---
  {
    id: "kol-801",
    city: "kolkata",
    latitude: 22.5530,
    longitude: 88.3530,
    decibel_level: 81.8,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Park Street Crossing (IoT #1)",
    notes: "Tram bell ring, vintage bus brake squeals & taxis",
    timestamp: new Date(Date.now() - 9 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "kol-802",
    city: "kolkata",
    latitude: 22.5720,
    longitude: 88.4330,
    decibel_level: 69.4,
    source_type: "iot_sensor",
    category: "industrial",
    location_name: "Salt Lake Sector V IT Hub",
    notes: "Commercial server farm backup generators",
    timestamp: new Date(Date.now() - 21 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "kol-803",
    city: "kolkata",
    latitude: 22.5850,
    longitude: 88.3410,
    decibel_level: 88.5,
    source_type: "crowdsourced",
    category: "traffic",
    location_name: "Howrah Station Approach Bridge",
    notes: "Massive ferry & railway commuter traffic hub",
    timestamp: new Date(Date.now() - 34 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "kol-804",
    city: "kolkata",
    latitude: 22.5110,
    longitude: 88.3610,
    decibel_level: 43.0,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Rabindra Sarobar Lake Quiet Zone",
    notes: "Lakeside green acoustic sanctuary sensor",
    timestamp: new Date(Date.now() - 58 * 60000).toISOString(),
    severity: "safe"
  },

  // --- AHMEDABAD ---
  {
    id: "ahm-901",
    city: "ahmedabad",
    latitude: 23.0300,
    longitude: 72.5180,
    decibel_level: 76.8,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "SG Highway Iscon Cross Roads (IoT #1)",
    notes: "High speed highway traffic & BRTS express bus transit",
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "ahm-902",
    city: "ahmedabad",
    latitude: 23.0060,
    longitude: 72.6010,
    decibel_level: 72.0,
    source_type: "crowdsourced",
    category: "loudspeakers",
    location_name: "Kankaria Lakefront Entertainment Zone",
    notes: "Amusement rides sound system & crowd noise",
    timestamp: new Date(Date.now() - 26 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "ahm-903",
    city: "ahmedabad",
    latitude: 23.0390,
    longitude: 72.5310,
    decibel_level: 46.8,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Science City Botanical Boulevard",
    notes: "Quiet educational campus acoustic monitor",
    timestamp: new Date(Date.now() - 44 * 60000).toISOString(),
    severity: "safe"
  },

  // --- JAIPUR ---
  {
    id: "jai-1001",
    city: "jaipur",
    latitude: 26.9180,
    longitude: 75.8150,
    decibel_level: 75.2,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "MI Road Ajmeri Gate Signal (IoT #1)",
    notes: "Heritage auto rickshaw stream & tourist bus idling",
    timestamp: new Date(Date.now() - 13 * 60000).toISOString(),
    severity: "violation"
  },
  {
    id: "jai-1002",
    city: "jaipur",
    latitude: 26.8530,
    longitude: 75.8050,
    decibel_level: 67.4,
    source_type: "iot_sensor",
    category: "traffic",
    location_name: "Malviya Nagar World Trade Park",
    notes: "Shopping mall parking ramp & arterial road",
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    severity: "moderate"
  },
  {
    id: "jai-1003",
    city: "jaipur",
    latitude: 26.9040,
    longitude: 75.8080,
    decibel_level: 42.6,
    source_type: "iot_sensor",
    category: "ambient",
    location_name: "Central Park Rambagh Acoustic Station",
    notes: "Central park green acoustic refuge baseline",
    timestamp: new Date(Date.now() - 51 * 60000).toISOString(),
    severity: "safe"
  }
];

export const INITIAL_MOCK_TRENDS = [
  { hour: "00:00", avg_db: 46.5, max_db: 61.0, min_db: 36.2, violations: 0 },
  { hour: "02:00", avg_db: 42.8, max_db: 57.5, min_db: 34.0, violations: 0 },
  { hour: "04:00", avg_db: 41.2, max_db: 54.0, min_db: 33.5, violations: 0 },
  { hour: "06:00", avg_db: 55.4, max_db: 70.8, min_db: 41.2, violations: 1 },
  { hour: "08:00", avg_db: 69.8, max_db: 84.5, min_db: 52.0, violations: 5 },
  { hour: "10:00", avg_db: 74.2, max_db: 89.6, min_db: 56.4, violations: 8 },
  { hour: "12:00", avg_db: 76.5, max_db: 92.4, min_db: 58.1, violations: 11 },
  { hour: "14:00", avg_db: 73.1, max_db: 87.2, min_db: 54.0, violations: 7 },
  { hour: "16:00", avg_db: 75.8, max_db: 90.5, min_db: 57.2, violations: 10 },
  { hour: "18:00", avg_db: 78.4, max_db: 93.8, min_db: 59.0, violations: 13 },
  { hour: "20:00", avg_db: 66.2, max_db: 79.5, min_db: 48.6, violations: 4 },
  { hour: "22:00", avg_db: 54.1, max_db: 68.2, min_db: 42.0, violations: 1 }
];
